### PR TITLE
 stream & copy files across storages

### PR DESCRIPTION
**Pull request by mayel**
- added a `copy` function to copy files across storages (eg. S3 -> Disk)
- added `stream` callback for storages

still to do:
- optimise further by using `S3.download_file(bucket, id, "path/to/file")` specifically when copying from S3 to Disk
- check that all copy paths (other than S3->Disk) work as expected
- add tests for the above (probably in capsule_supplement?)

### CODE REVIEW

**Comment by mayel** [comment]
I hope this is within the scope of this library :) Needed this functionality to implement migrations and export of user data.

**Comment by tfwright** [comment]
Hi again @mayel happy to see you've taken an interest in Capsule.

I think there is definitely some good stuff here. A separate stream api makes a lot of sense especially in the Elixir ecosystem. I planned on eventually adding it myself but never got around to it so thank again for taking the initiative on that!

Copy is something I used to support, but I removed it because as stated in the README copying ("promoting) is pretty trivial using put: https://github.com/elixir-capsule/capsule#locator

In any case, if you are willing to break out these changes into separate more focused PRs we can discuss more there.

**Comment by mayel** [comment]
Apologies, I had forgotten you'd replied here @tfwright. 

Please correct me if I'm wrong, but it sounds to me from this and your [other](https://github.com/elixir-capsule/capsule/pull/12#issuecomment-1839239968) [messages](https://github.com/elixir-capsule/supplement/pull/12#issuecomment-1904961148) that you're not really interested in these contributions in which case I'll simply withdraw.

**Comment by tfwright** [comment]
@mayel I went ahead and closed them. If you feel like trying out the stream functionality I added please feel free to open an issue with thoughts/suggestions

**Pull request closed without merging**
